apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: curl
spec:
  params:
   - name: url
     description: URL to curl'ed
     type: string
   - name: options
     description: options of url
     type: array
     default: []
  steps:
    - name: curl
      image: curlimages/curl
      command: [curl]
      args: ["$(params.options[*])", "$(params.url)"]
